[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.58.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.1"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.58"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
